server:
  port: 8089
  error:
    whitelabel:
      enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true;
  datasource:
    url: jdbc:h2:./db/jobsearchdb;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.yandex.ru
    username: conovalov.elizar@yandex.ru
    password: obmimyygyoqxtifs
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  file:
    name: logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  level:
    root: INFO
    org:
      springframework:
        security: debug
      hibernate:
        type: trace
    sql: trace
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
