--liquibase formatted sql
--changeset angryelizar:24-insert_new_contact_info

INSERT INTO CONTACTS_INFO(TYPE_ID, RESUME_ID, CONTENT)
VALUES ((select id from CONTACT_TYPES where TYPE = 'WhatsApp'),
        (select id from RESUMES where NAME = 'Юрист со знанием английского языка'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Telegram'),
        (select id from RESUMES where NAME = 'Разработчик Java'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Телефон'),
        (select id from RESUMES where NAME = 'Менеджер по продажам'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'WhatsApp'),
        (select id from RESUMES where NAME = 'Финансовый аналитик'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Telegram'),
        (select id from RESUMES where NAME = 'Дизайнер UX/UI'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Телефон'),
        (select id from RESUMES where NAME = 'HR-менеджер'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'WhatsApp'),
        (select id from RESUMES where NAME = 'Администратор систем'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Telegram'),
        (select id from RESUMES where NAME = 'Бухгалтер'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Телефон'),
        (select id from RESUMES where NAME = 'Архитектор'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'WhatsApp'),
        (select id from RESUMES where NAME = 'Маркетолог'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Telegram'),
        (select id from RESUMES where NAME = 'Автоэлектрик-диагност'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Телефон'),
        (select id from RESUMES where NAME = 'Frontend-разработчик'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Телефон'),
        (select id from RESUMES where NAME = 'Медицинская сестра'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'WhatsApp'),
        (select id from RESUMES where NAME = 'Системный администратор'), '+996123321123'),
       ((select id from CONTACT_TYPES where TYPE = 'Telegram'),
        (select id from RESUMES where NAME = 'Художник-иллюстратор'), '+996123321123');
