--liquibase formatted sql
--changeset angryelizar:25-insert_new_work_experience_info

INSERT INTO WORK_EXPERIENCE_INFO(RESUME_ID, YEARS, COMPANY_NAME, POSITION, RESPONSIBILITIES)
VALUES ((select id from RESUMES where NAME = 'Юрист со знанием английского языка'), 5, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Разработчик Java'), 4, 'Яндекс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Менеджер по продажам'), 5, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Финансовый аналитик'), 5, 'Яндекс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Дизайнер UX/UI'), 5, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'HR-менеджер'), 10, 'Яндекс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Администратор систем'), 5, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Бухгалтер'), 3, 'Google',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Архитектор'), 5, 'Google',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Маркетолог'), 1, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Автоэлектрик-диагност'), 5, 'Google',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Frontend-разработчик'), 2, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Медицинская сестра'), 5, 'Google',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Системный администратор'), 5, 'ОсОО Прогресс',
        'Директор директора', 'Управление компанией'),
       ((select id from RESUMES where NAME = 'Художник-иллюстратор'), 5, 'Google',
        'Директор директора', 'Управление компанией');